title: Garrett Springer's Portfolio
description:
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

relative_links:
  enabled: true
  collections: true

collections:
  _posts:
    permalink: /_posts/:path/

markdown: GFM