title: The Analytics Atlas
description: A Guide Through the World of Data
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

relative_links:
  enabled: true
  collections: true

collections:
  _posts:
    permalink: /_posts/:path/
